modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/anviaan/SimpleMango/issues"

[[mods]]
modId="simplemango"
version="1.2.0"
displayName="SimpleMango Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-mango"
authors="anvian"

description="Adds a food Mango!, which has a new type of wood and a new fruit, new trades and more."

[[dependencies.simplemango]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplemango]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
