modLoader="javafml"
loaderVersion="[43,)"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU GPLv3"
issueTrackerURL="https://github.com/anviaan/SimpleMango/issues"

[[mods]]
modId="simplemango"
version="1.3.0"
displayName="SimpleMango Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-mango"
authors="anvian"
description="Adds a food Mango!, which has a new type of wood and a new fruit, new trades and more."

[[dependencies.simplemango]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplemango]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
